### ISSUE TITLE
problem using .discriminator with mongoose-multitenant

### ISSUE THREAD

**Issue by anoopsinghbayes** [jraede/mongoose-multitenant#7]
Hi there,
i am trying to use .discriminator provided by mongoose to inherit from a base class so that they can be saved in the same collection distinguished by a _type key but trying yo use this with mongoose-multitenant plugin gives weird output,

I used the following example to use discriminator key

```
   function BaseSchema() {
  Schema.apply(this, arguments);

  this.add({
    name: String,
    createdAt: Date
  });
}
util.inherits(BaseSchema, Schema);

var PersonSchema = new BaseSchema();
var BossSchema = new BaseSchema({ department: String });

var Person = mongoose.mtModel('Person', PersonSchema);
var Boss = Person.discriminator('Boss', BossSchema);
```

what should actually happen when i use this with multi-tenant plugin is both boss and person data should be saved in t1_person collection(t1 begin the tenant id )
but boss data goes in t1_boss collection and person data goes in t2_person collection

**Comment by jraede** [comment]
Unfortunately I don't really have time to investigate and address this since I'm still not sure I understand what the issue is. A failing test would save me a lot of time since I could just modify the code so it will pass. If you feel comfortable then you're more than welcome to make a change and submit a PR.

Thanks

**Comment by Mickael-van-der-Beek** [comment]
Ok, I encountered the same issue and it can be reproduced by following these steps:

- create a first model ```mA``` with schema ```sA``` in collection ```cA```
- create a second model ```mB``` with schema ```sB``` which inherits from ```sA``` in the same collection ```cA```
- create a document ```dA```, instance of model ```mA``` and save it
- create a document ```dB```, instance of model ```mB``` and save it
- make an empty find query (find all) for the model ```mB```

The results will be an Array containing both ```dA``` and ```dB``` which shouldn't happen since they both have a different discriminator key value (the ```__t``` key).

Querying ```mA``` should only return instances of ```mA```, which means ```dA``` and ```mB``` should only return instances of ```mB```, which means ```dB```.

Here's a test script with both schema inheritance (```mongoose-schema-extend```) and multi-tenancy (```mongoose-multitenant```):
```
var mongoose = require('mongoose');
var assert = require('assert');
var async = require('async');

require('mongoose-multitenant')('_');
require('mongoose-schema-extend');

mongoose.connect('mongodb://localhost:27017/mtenant_bug', {});

var ParentSchema = new (mongoose.Schema)({
	__t: {
		type: 'String'
	},
	name: {
		type: 'String'
	},
	isParent: {
		type: 'Boolean'
	}
}, {
	discriminatorKey: '__t'
});

mongoose.mtModel('Parent', ParentSchema);

var ChildSchema = ParentSchema.extend({
	isChild: {
		type: 'Boolean'
	}
});

mongoose.mtModel('Child', ChildSchema, 'parents');

var tenantId = 'testing';

async.series([
	function (cb) {
		mongoose.mtModel(tenantId + '.Parent')({
			name: 'MyParent'
		})
		.save(cb);
	},
	function (cb) {
		mongoose.mtModel(tenantId + '.Child')({
			name: 'MyChild'
		})
		.save(cb);
	},
	function (cb) {
		mongoose.mtModel(tenantId + '.Child')
		.find()
		.exec(cb);
	}
], function (e, results) {
	if (e) {
		throw e;
	}

	var children = results.pop();

	console.log(children);

	assert.strictEqual(Array.isArray(children), true);
	assert.strictEqual(children.length, 1);
	assert.strictEqual(
		children.reduce(function (consistent, child) {
			return consistent && child.__t === mongoose.mtModel(tenantId + '.Child').modelName;
		}, true),
		true
	);

	console.log('End.');
});
```

To run this scripts you will need to install the following NPM modules:

- ```mongoose``` and ```mongoose-multitenant``` for obvious reasons
- ```mongoose-schema-extend``` which will let you do schema inheritance
- ```async``` just for the flow control of this test case

The point of ```mongoose-schema-extend``` is,  like I said, used to do schema inheritance which means:

- extend the parent's schema
- extending the event hooks (post / pre)
- extending or overriding the statics / methods of a model

By specifying the collection name (third) argument in the model constructor you can also have multiple different models in the same collection. See my example for this exact case.

**Comment by Mickael-van-der-Beek** [comment]
You can ignore my latest post, this was my own damn fault because I was working with the false assumption that doing a ```find()``` on a child model would only return documents with that model's ```__t```.

Here's the feature request for the ```mongoose-schema-extend``` module:

https://github.com/briankircho/mongoose-schema-extend/issues/26

**Comment by jraede** [comment]
Sounds good. Thanks for the clarification!

**Comment by Mickael-van-der-Beek** [comment]
Ok, I found the issue in the end. It's not ```mongoose-multinenants```'s fault.

The issue occurs when combining both the ```mongoose-multinenant``` and ```mongoose-schema-extend``` plugins and is due to the fact that internally, ```mongoose-schema-extend```, uses ```model()``` rather than ```mtModel()```. e.g:

https://github.com/briankircho/mongoose-schema-extend/blob/master/index.js#L63
